# Generated by Django 2.0.4 on 2018-04-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaAccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Initiator', models.CharField(default=None, max_length=30)),
                ('CommandID', models.CharField(default=None, max_length=30)),
                ('PartyA', models.CharField(default=None, max_length=30)),
                ('IdentifierType', models.CharField(default=None, max_length=30)),
                ('Remarks', models.TextField(default=None)),
                ('AccountType', models.CharField(default=None, max_length=30)),
                ('date_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaB2C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_name', models.CharField(default=None, max_length=30)),
                ('command_id', models.CharField(default=None, max_length=30)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=30)),
                ('party_a', models.CharField(default=None, max_length=30)),
                ('party_b', models.CharField(default=None, max_length=30)),
                ('remarks', models.TextField(default=None)),
                ('occasion', models.CharField(default=None, max_length=30)),
                ('date_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaC2B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommandID', models.CharField(default=None, max_length=30)),
                ('Amount', models.DecimalField(decimal_places=5, max_digits=30)),
                ('MSISDN', models.CharField(default=None, max_length=30)),
                ('BillRefNumber', models.CharField(default=None, max_length=30)),
                ('ShortCode', models.CharField(default=None, max_length=10)),
                ('Remarks', models.TextField(default=None)),
                ('date_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaReversals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessShortCode', models.CharField(default=None, max_length=30)),
                ('Password', models.CharField(default=None, max_length=30)),
                ('Timestamp', models.DateTimeField()),
                ('TransactionType', models.CharField(default=None, max_length=30)),
                ('Amount', models.DecimalField(decimal_places=5, max_digits=30)),
                ('PartyA', models.CharField(default=None, max_length=30)),
                ('PartyB', models.CharField(default=None, max_length=30)),
                ('PhoneNumber', models.CharField(default=None, max_length=30)),
                ('AccountReference', models.CharField(default=None, max_length=30)),
                ('TransactionDesc', models.TextField(default=None)),
                ('date_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Initiator', models.CharField(default=None, max_length=30)),
                ('CommandID', models.CharField(default=None, max_length=30)),
                ('TransactionID', models.CharField(default=None, max_length=30)),
                ('PartyA', models.CharField(default=None, max_length=30)),
                ('IdentifierType', models.CharField(default=None, max_length=30)),
                ('Remarks', models.TextField(default=None)),
                ('Occasion', models.CharField(default=None, max_length=30)),
                ('date_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
