from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser

from django.core.validators import RegexValidator

class UserProfile(AbstractUser):
    """
    User model
    """
    phone_regex = RegexValidator(
        regex=r'(\d{3})\D*(\d{3})\D*(\d{4})$',  # r'^d{7,12}$',
        message="Phone Number must be entered in the format: '999999999'. Up to 12 digits allowed."
    )  # r'^\+?1?\d{9,15}$'
    phone = models.CharField(
        max_length=12,
        blank=True,
        validators=[phone_regex]
    )
    # address
    # city
    # state
    # country


class MpesaB2C(models.Model):
    """
    InitiatorName - This is the credential/username used to authenticate the transaction request.

    CommandID - Unique command for each transaction type e.g. SalaryPayment, BusinessPayment, PromotionPayment

    Amount - The amount being transacted

    PartyA - Organization’s shortcode initiating the transaction.

    PartyB - Phone number receiving the transaction

    Remarks - Comments that are sent along with the transaction.

    Occasion - Optional
    """
    initiator_name = models.CharField(default=None, max_length=30)
    command_id = models.CharField(default=None, max_length=30)
    amount = models.DecimalField(max_digits=30, decimal_places=5)
    party_a = models.CharField(default=None, max_length=30)
    party_b = models.CharField(default=None, max_length=30)
    remarks = models.TextField(default=None)
    occasion = models.CharField(default=None, max_length=30)
    date_entry = models.DateTimeField(null=True, auto_now_add=True)
    last_modified = models.DateTimeField(null=True, auto_now=True)


class MpesaC2B(models.Model):
    """
    CommandID - Unique command for each transaction type.
    Amount - The amount been transacted.
    MSISDN - MSISDN (phone number) sending the transaction, start with country code without the plus(+) sign.
    BillRefNumber - Bill Reference Number (Optional).
    ShortCode - 6 digit M-Pesa Till Number or PayBill Number
    """
    CommandID = models.CharField(default=None, max_length=30)
    Amount = models.DecimalField(max_digits=30, decimal_places=5)
    MSISDN = models.CharField(default=None, max_length=30)
    BillRefNumber = models.CharField(default=None, max_length=30)
    ShortCode = models.CharField(default=None, max_length=10)
    Remarks = models.TextField(default=None)
    date_entry = models.DateTimeField(null=True, auto_now_add=True)
    last_modified = models.DateTimeField(null=True, auto_now=True)


class MpesaAccountBalance(models.Model):
    """
    Initiator - This is the credential/username used to authenticate the transaction request.
    CommandID - A unique command passed to the M-Pesa system.
    PartyA - The shortcode of the organisation receiving the transaction.
    ReceiverIdentifierType - Type of the organisation receiving the transaction.
    Remarks - Comments that are sent along with the transaction.
    AccountType - Organisation receiving the funds.
    """
    Initiator = models.CharField(default=None, max_length=30)
    CommandID = models.CharField(default=None, max_length=30)
    PartyA = models.CharField(default=None, max_length=30)
    IdentifierType = models.CharField(default=None, max_length=30)
    Remarks = models.TextField(default=None)
    AccountType = models.CharField(default=None, max_length=30)
    date_entry = models.DateTimeField(null=True, auto_now_add=True)
    last_modified = models.DateTimeField(null=True, auto_now=True)


class TransactionStatus(models.Model):
    """
    CommandID 	Unique command for each transaction type, possible values are: TransactionStatusQuery.
    ShortCode 	Organization /MSISDN sending the transaction.
    IdentifierType 	Type of organization receiving the transaction
    Remarks 	Comments that are sent along with the transaction.
    Initiator 	The name of Initiator to initiating the request.
    TransactionID 	Organization Receiving the funds.
    Occasion 	Optional.
    """
    Initiator = models.CharField(default=None, max_length=30)
    CommandID = models.CharField(default=None, max_length=30)
    TransactionID = models.CharField(default=None, max_length=30)
    PartyA = models.CharField(default=None, max_length=30)
    IdentifierType = models.CharField(default=None, max_length=30)
    Remarks = models.TextField(default=None)
    Occasion = models.CharField(default=None, max_length=30)
    date_entry = models.DateTimeField(null=True, auto_now_add=True)
    last_modified = models.DateTimeField(null=True, auto_now=True)


class MpesaReversals(models.Model):
    """
    BusinessShortCode 	The organization shortcode used to receive the transaction.
    Password 	The password for encrypting the request. This is generated by base64 encoding BusinessShortcode, Passkey and Timestamp.
    Timestamp 	The timestamp of the transaction in the format yyyymmddhhiiss.
    TransactionType 	The transaction type to be used for this request. Only CustomerPayBillOnline is supported.
    Amount 	The amount to be transacted.
    PartyA 	The MSISDN sending the funds.
    PartyB 	The organization shortcode receiving the funds
    PhoneNumber 	The MSISDN sending the funds.
    AccountReference 	Used with M-Pesa PayBills.
    TransactionDesc 	A description of the transaction.
    """
    BusinessShortCode = models.CharField(default=None, max_length=30)
    Password = models.CharField(default=None, max_length=30)
    Timestamp = models.DateTimeField()
    TransactionType = models.CharField(default=None, max_length=30)
    Amount = models.DecimalField(max_digits=30, decimal_places=5)
    PartyA = models.CharField(default=None, max_length=30)
    PartyB = models.CharField(default=None, max_length=30)
    PhoneNumber = models.CharField(default=None, max_length=30)
    AccountReference = models.CharField(default=None, max_length=30)
    TransactionDesc = models.TextField(default=None)
    date_entry = models.DateTimeField(null=True, auto_now_add=True)
    last_modified = models.DateTimeField(null=True, auto_now=True)
